project:
  type: book
  output-dir: docs

book:
  title: "Introduction to brms"
  author: "Tara Pozzi and Wesley Brooks"
  date: "11-08-2023"
  
  search: true
  repo-url: https://github.com/d-rug/intro_to_brms
  downloads: [pdf]
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_brms.qmd
    - 03_example.qmd
    - 04_resources.qmd
  
  sidebar:
    logo: https://github.com/d-rug/d-rug.github.io/raw/main/DRUG_final_cobalt.png
  site-url: https://d-rug.github.io

format:
  html:
    theme: cosmo
    number-sections: false